<?php

return [
    "categories" => [
        [
            "name" => "Cinese",
            // 0
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/chinese.png"
        ],
        [
            "name" => "Pizza",
            // 1
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/pizza.png"
        ],
        [
            "name" => "Italiano",
            // 2
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/italian.png"
        ],
        [
            "name" => "Kebab",
            // 3
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/deli.png"
        ],
        [
            "name" => "Americano",
            // 4
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/american.png"
        ],
        [
            "name" => "Giapponese",
            // 5
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/japanese.png"
        ],
        [
            "name" => "Poke",
            // 6
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/asian.png"
        ],
        [
            "name" => "Africano",
            // 7
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/bbq.png"
        ],
        [
            "name" => "Arabo",
            // 8
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/streetfood.png"
        ],
        [
            "name" => "Bakery",
            // 9
            "image" => "https://ouch-cdn2.icons8.com/-mxg5TJ7zDo6BwVahzJ36A5DMg432lM-hB5DXHkfkus/rs:fit:256:192/czM6Ly9pY29uczgu/b3VjaC1wcm9kLmFz/c2V0cy9wbmcvOTQ2/L2VjOGNhYzkwLTM0/MTAtNDVjYi1hMDM0/LTI5MjVkZjZlZmQ4/My5wbmc.png"
        ],
        [
            "name" => "Egiziano",
            // 10
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Messicano",
            // 11
            "image" => "https://cdn.pixabay.com/photo/2013/07/13/09/37/taco-155812_960_720.png"
        ],
        [
            "name" => "Focacce",
            // 12
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/comfortfood.png"
        ],
        [
            "name" => "Fritti",
            // 13
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/fastfood.png"
        ],
        [
            "name" => "Gourmet",
            // 14
            "image" => "https://previews.123rf.com/images/emojiimage/emojiimage2003/emojiimage200301082/143013384-grande-cucina-con-meticolosa-preparazione-del-cibo-e-servizio-su-piastra-con-illustrazione-vettorial.jpg"
        ],
        [
            "name" => "Colazione",
            // 15
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/cantonese.png"
        ],
        [
            "name" => "Vegano",
            // 16
            "image" => "https://d4p17acsd5wyj.cloudfront.net/shortcuts/cuisines/seafood.png"
        ]

    ],
    "ingredients" => [
        'Pomodoro san marzano dop',
        'Mozzarella fiordilatte',
        'Olio extravergine',
        'Funghi',
        'Prosciutto cotto',
        'Prosciutto crudo',
        'Mortadella',
        'Salsiccia',
        'Rucola',
        'Pomodorini',
        'Melanzane',
        'Peperoni',
        'Zucchine',
        'Bresaola',
        'Speck',
        'Wurstel',
        'Olive',
        'Scamorza',
        'Mozzarella di bufala',
        'Cipolla'
    ],
    'types' => [
        'Colazione',
        // 0
        'Antipasti',
        // 1
        'Primi piatti',
        // 2
        'Secondi',
        // 3
        'Carne',
        // 4
        'Pesce',
        // 5
        'Desserts',
        // 6
        'Bevande',
        // 7
        'Pizze',
        // 8
        'Fritti',
        // 9
        'Contorni',
        // 10
        'Insalate',
        // 11
        'Focacce',
        // 12
        'Hamburgers',
        // 13
        'Panini',
        // 14
        'Frutta',
        // 15
        'Kebab',
        // 16 per kabbabbaro
        'Zuppe',
        // 17 per africani-giapponesi-cinesi
        'Sushi',
        // 18 per giapponesi
        'Gyoza',
        // 19 per cinesi-giapponesi
        'Street Food',
        // 20
        'Koshari',
        // 21 per egiziano
        'Tacos',
        // 22 per messicano
        'Burritos' // 23 per messicano

    ],
    'products' => [

        [
            "name" => "Zuppa di Miso",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/timoelenticchie/wp-content/uploads/2020/07/Zuppa-di-shiro-miso-tiepida-3-e1595398065106.jpeg",
            "description" => "Zuppa di verdure a base di fagioli di soia",
            "type_id" => 3,
            "restaurant_id" => [11, 6],
        ],
        [
            "name" => "Risotto ai Funghi Porcini",
            "price" => "15.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.cucchiaio.it/content/uploads/2018/03/risotto-ai-funghi-porcini.jpg",
            "description" => "Risotto con funghi porcini freschi e parmigiano reggiano",
            "type_id" => 2,
            "restaurant_id" => [4, 9],
        ],
        [
            "name" => "Pollo alla Griglia",
            "price" => "12.00",
            "available" => '1',
            "discount" => "10",
            "image" => "https://www.gustoblog.it/wp-content/uploads/2019/06/pollo-alla-griglia-ricetta-e-consigli-per-una-cucina-sana-e-leggera.jpg",
            "description" => "Petto di pollo marinato e grigliato con verdure",
            "type_id" => 1,
            "restaurant_id" => [1, 6],
        ],
        [
            "name" => "Pizza Margherita",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2019/06/pizza-margherita-ricetta-originale-napoletana.jpg",
            "description" => "Pizza con salsa di pomodoro, mozzarella e basilico",
            "type_id" => 4,
            "restaurant_id" => [7, 8],
        ],
        [
            "name" => "Spaghetti alla Carbonara",
            "price" => "10.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2019/06/spaghetti-alla-carbonara-ricetta-originale.jpg",
            "description" => "Spaghetti con pancetta, uova, pecorino e pepe",
            "type_id" => 2,
            "restaurant_id" => [2, 11],
        ],

    

        [
            "name" => "Zuppa con Pollo e Mais",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.giallozafferano.it/images/240-24009/Zuppa-di-legumi-e-cereali_650x433_wm.jpg",
            "description" => "Zuppa cpn uovo, pollo e mais",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [11],
        ],
        // fine zuppe ristorante cinese
        [
            "name" => "Gnocchi di Riso con Gamberi e Verdure",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.farinadelmiosacco.com/wp-content/uploads/2014/02/gnocchi_di_riso_saltati_con_gamberi_e_verdure.jpg",
            "description" => null,
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [11],
        ],
        [
            "name" => "Spaghetti di Soia con Carne e Verdure",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2022/01/spaghetti-soia/jcr:content/page_images/ogImage.img10.jpg/1641910799301.jpg",
            "description" => null,
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [11],
        ],
        [
            "name" => "Spaghetti al pomodoro",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.basilicata24.it/photogallery_new/images/2017/11/spaghetti-28136.660x368.jpg",
            "description" => null,
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Carbonara",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/albe/wp-content/uploads/2020/08/15FA1142-B5FA-410C-878B-2B8745B85F64.jpeg",
            "description" => null,
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine primi ristorante cinese
        [
            "name" => "Involtino Primavera",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/Involtini-primavera-cinesi.jpg",
            "description" => "Involtino fritto ripieno di verdure",
            "type_id" => 2,
            "restaurant_id" => [2, 6],
        ],
        [
            "name" => "Riso alle Verdure",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2018/04/Riso-alle-verdure.jpg",
            "description" => "Riso bianco con verdure miste saltate in padella",
            "type_id" => 4,
            "restaurant_id" => [1, 7],
            ],
            [
            "name" => "Pad Thai",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2018/04/Pad-Thai-1024x683.jpg",
            "description" => "Noodles stir-fry con gamberi, verdure e salsa di arachidi",
            "type_id" => 1,
            "restaurant_id" => [4, 9],
            ],
            [
            "name" => "Tacos di Pesce",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustissimo.it/wp-content/uploads/2019/05/tacos-di-pesce.jpg",
            "description" => "Tacos di pesce fritto con salsa guacamole e panna acida",
            "type_id" => 5,
            "restaurant_id" => [5, 8],
            ],
            [
            "name" => "Couscous alla Marocchina",
            "price" => "6.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2018/04/couscous-alla-marocchina.jpg",
            "description" => "Couscous di semola con verdure e spezie marocchine",
            "type_id" => 6,
            "restaurant_id" => [3, 11],
            ],
            [
            "name" => "Curry Indiano",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.gustoblog.it/wp-content/uploads/2018/04/curry-indiano.jpg",
            "description" => "Curry di pollo con verdure e spezie indiane",
            "type_id" => 7,
            "restaurant_id" => [10, 12],
            ],
            [
                "name" => "Ramen",
                "price" => "8.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.gastronomia.it/wp-content/uploads/2019/11/Ramen.jpg",
                "description" => "Zuppa di noodles in brodo di pollo e maiale",
                "type_id" => 1,
                "restaurant_id" => [11, 4],
                ],
                
                [
                "name" => "Tempura",
                "price" => "7.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.gastronomia.it/wp-content/uploads/2019/11/tempura-735x400.jpg",
                "description" => "Verdure o frutti di mare fritti in pastella di riso",
                "type_id" => 2,
                "restaurant_id" => [1, 6],
                ],
                
                [
                "name" => "Sushi",
                "price" => "10.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.gastronomia.it/wp-content/uploads/2019/11/sushi-735x400.jpg",
                "description" => "Riso condito con aceto di riso, zucchero e sale, con diversi ripieni tra cui pesce crudo",
                "type_id" => 3,
                "restaurant_id" => [2, 9],
                ],
                
                [
                "name" => "Teriyaki",
                "price" => "12.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.gastronomia.it/wp-content/uploads/2019/11/teriyaki-735x400.jpg",
                "description" => "Carne o pesce grigliato con salsa di soia, zucchero e sake",
                "type_id" => 4,
                "restaurant_id" => [5, 11],
                ],
                
                [
                "name" => "Donburi",
                "price" => "9.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.gastronomia.it/wp-content/uploads/2019/11/donburi-735x400.jpg",
                "description" => "Piatto a base di riso servito con diverse combinazioni di ingredienti come carne, uova o pesce",
                "type_id" => 5,
                "restaurant_id" => [3, 8],
                ],

        [
            "name" => "Tofu Crudo",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://thumbs.dreamstime.com/b/tofu-crudo-30530074.jpg",
            "description" => "Preparazione a base di soia condita con salsa cinese",
            "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => [6],
        ],
        // fine antipasto cinese
        [
            "name" => "Yasai Gyoza",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.mrsjoneskitchen.com/wp-content/uploads/2021/11/Yasai-gyoza-vegetable-dumplings-recipe.jpg",
            "description" => "Ravioli vegetariani",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [2, 6],
        ],

        [
            "name" => "Ebi Gyoza",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.youkimagenta.it/wp-content/uploads/2020/03/04a.jpg",
            "description" => "Ravioli giapponesi con ripieno di gamberi",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [2],
        ],
        // fine gyoza cinese
        [
            "name" => "Santa Cruz Wrap",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://media-cdn.tripadvisor.com/media/photo-s/12/7a/ae/7d/santa-cruz-wrap.jpg",
            "description" => "Tortilla di grano farcita con petto di pollo speziato, leggermente piccante, lattuga, formaggio fuso e salsa Cheddar.",
            "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => [7],
        ],
        [
            "name" => "Cheeseburger",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.recipetineats.com/wp-content/uploads/2022/08/Stack-of-cheeseburgers.jpg",
            "description" => "Hamburger di scottona, formaggio cheddar, cetrioli fatti in casa e salsa ketchup racchiusi in un morbido bun artigianale",
            "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => [4, 7],
        ],

        [
            "name" => "Gran Crispy Clover",
            "price" => "13.20",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.todis.it/wp-content/uploads/2020/05/giornata-mondiale-dell-hamburger-.jpg",
            "description" => "Doppio hamburger di scottona, doppio formaggio cheddar, doppio bacon e doppio strato di salsa Clover crispy racchiusi in un morbido bun artigianale",
            "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => [4, 7],
        ],

        [
            "name" => "American Burger",
            "price" => "10.80",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.buttalapasta.it/wp-content/uploads/2016/01/hamburger-di-carne-americano.jpg",
            "description" => "Hamburger di scottona, insalata iceberg, formaggio cheddar, bacon, pomodoro fresco, la nostra cipolla caramellata e salsa BBQ racchiusi in un morbido bun artigianale",
            "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => [7],
        ],
        // fine hamburger
        [
            "name" => "Marinara",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.pizzatales.it/wp50/wp-content/uploads/2021/02/WhatsApp-Image-2021-02-19-at-09.04.21.jpeg",
            "description" => "Pomodoro San Marzano DOP, aglio, origano, olio evo della Penisola Sorrentina DOP e basilico",
            "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],

        [
            "name" => "Margherita",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://images.dissapore.com/wp-content/uploads/2017/05/PepeMargheritaWide.jpg",
            "description" => "Pomodoro e mozzarella",
            "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],
        [
            "name" => "Taco di Carne",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/tacos-carne.jpg",
            "description" => "Taco ripieno di carne di manzo e verdure",
            "type_id" => 1,
            "restaurant_id" => [3, 7],
            ],
            [
            "name" => "Quesadilla di Pollo",
            "price" => "6.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/quesadilla-pollo.jpg",
            "description" => "Quesadilla ripiena di pollo e formaggio",
            "type_id" => 1,
            "restaurant_id" => [3, 9],
            ],
            [
            "name" => "Burrito di Mais",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/burrito-mais.jpg",
            "description" => "Burrito ripieno di mais, fagioli e verdure",
            "type_id" => 1,
            "restaurant_id" => [3, 5],
            ],
            [
            "name" => "Chimichanga di Tacchino",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/chimichanga-tacchino.jpg",
            "description" => "Chimichanga fritta ripiena di tacchino e verdure",
            "type_id" => 1,
            "restaurant_id" => [3, 4],
            ],
            [
                "name" => "Pokè Bowl di Tonno",
                "price" => "7.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.sapore.it/wp-content/uploads/2019/07/poke-bowl-di-tonno-1-720x720.jpg",
                "description" => "Pokè Bowl di Tonno con riso, avocado e salsa teriyaki",
                "type_id" => 5,
                "restaurant_id" => [1, 4],
                ],
                [
                "name" => "Pokè Bowl di Salmone",
                "price" => "8.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.foodlover.it/wp-content/uploads/2018/06/Poke-Bowl-salmone-e-avocado.jpg",
                "description" => "Pokè Bowl di Salmone con riso, avocado e salsa sriracha",
                "type_id" => 5,
                "restaurant_id" => [2, 4],
                ],
                [
                "name" => "Pokè Bowl di Gamberi",
                "price" => "9.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.starbene.it/wp-content/uploads/2018/03/Poke-Bowl-Gamberi-e-Avocado.jpg",
                "description" => "Pokè Bowl di Gamberi con riso, avocado e salsa wasabi",
                "type_id" => 5,
                "restaurant_id" => [3, 4],
                ],
                [
                "name" => "Pokè Bowl di Tofu",
                "price" => "6.00",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.cucchiaio.it/content/uploads/2019/03/poke-bowl-tofu.jpg",
                "description" => "Pokè Bowl di Tofu con riso, avocado e salsa di soia",
                "type_id" => 5,
                "restaurant_id" => [1, 3],
                ],
                [
                "name" => "Pokè Bowl di Tonno e Avocado",
                "price" => "8.50",
                "available" => '1',
                "discount" => null,
                "image" => "https://www.cucina-naturale.it/wp-content/uploads/2020/04/poke-bowl-tonno-avocado.jpg",
                "description" => "Pokè Bowl di Tonno e Avocado con riso, cetriolo e salsa wasabi",
                "type_id" => 5,
                "restaurant_id" => [2, 3],
                ],
            [
            "name" => "Enchiladas di Tacchino",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/04/enchiladas-tacchino.jpg",
            "description" => "Enchiladas ripiene di tacchino e formaggio",
            "type_id" => 1,
            "restaurant_id" => [3, 6],
            ],

        [
            "name" => "Battipagliese",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://delivery.rossopomodoro.it/monza/5962-large_default/pi159-battipagliese.jpg",
            "description" => "Datterino giallo di Battipaglia, provola affumicata, olive e capperi, basilico e peperoncino",
            "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Bianca, cotto e funghi",
            "price" => "10.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/lacucinadirosalba/wp-content/uploads/2020/12/PIZZA-BIANCA-AI-FUNGHI_DSC2758_00001.jpg",
            "description" => "Mozzarella, fior di panna, funghi champignon, prosciutto cotto Fiorucci, basilico",
            "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],
        [
            "name" => "IPA",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.birrafriulana.it/wp-content/uploads/2019/06/ipa-birra.jpg",
            "description" => "Birra IPA con sentori di agrumi e resina",
            "type_id" => 5,
            "restaurant_id" => [1, 3],
            ],
            [
            "name" => "Stout",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.birrafriulana.it/wp-content/uploads/2019/06/stout-birra.jpg",
            "description" => "Birra Stout scura con sentori di caffè e cioccolato",
            "type_id" => 5,
            "restaurant_id" => [5, 7],
            ],
            [
            "name" => "Pilsner",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.birrafriulana.it/wp-content/uploads/2019/06/pilsner-birra.jpg",
            "description" => "Birra Pilsner chiara con una nota amara equilibrata",
            "type_id" => 5,
            "restaurant_id" => [9, 11],
            ],
            [
            "name" => "Blonde Ale",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.birrafriulana.it/wp-content/uploads/2019/06/blonde-ale-birra.jpg",
            "description" => "Birra Blonde Ale leggera e rinfrescante con sentori di malto",
            "type_id" => 5,
            "restaurant_id" => [2, 4],
            ],
            [
            "name" => "Wheat Beer",
            "price" => "4.75",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.birrafriulana.it/wp-content/uploads/2019/06/wheat-beer-birra.jpg",
            "description" => "Birra Wheat Beer con sentori di frumento e agrumi",
            "type_id" => 5,
            "restaurant_id" => [6, 8],
            ],

        // fine pizze
        [
            "name" => "Bruschetta alla 'Nduja",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.specialitapizzimenti.com/wp-content/uploads/2020/06/bruschetta-pomodoro-nduja.jpg",
            "description" => "Bruschetta con 'nduja calabrese, stracciatella fresca e olio al basilico",
            "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Chianti Classico",
            "price" => "15.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.vinicius.it/wp-content/uploads/2018/06/chianti-classico-riserva.jpg",
            "description" => "Vino rosso prodotto nella regione toscana",
            "type_id" => 5,
            "restaurant_id" => [1, 3],
            ],
            [
            "name" => "Pinot Noir",
            "price" => "20.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.vinimania.it/wp-content/uploads/2019/06/Pinot-Noir-1.jpg",
            "description" => "Vino rosso leggero e fruttato",
            "type_id" => 5,
            "restaurant_id" => [4, 7],
            ],
            [
            "name" => "Sauvignon Blanc",
            "price" => "18.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.vinimania.it/wp-content/uploads/2019/06/Sauvignon-Blanc.jpg",
            "description" => "Vino bianco leggero e asciutto",
            "type_id" => 5,
            "restaurant_id" => [5, 9],
            ],
            [
            "name" => "Prosecco",
            "price" => "16.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.vinimania.it/wp-content/uploads/2019/06/Prosecco.jpg",
            "description" => "Vino spumante dolce prodotto in Veneto",
            "type_id" => 5,
            "restaurant_id" => [6, 11],
            ],
            [
            "name" => "Cabernet Sauvignon",
            "price" => "22.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.vinimania.it/wp-content/uploads/2019/06/Cabernet-Sauvignon.jpg",
            "description" => "Vino rosso intenso e strutturato",
            "type_id" => 5,
            "restaurant_id" => [8, 10],
            ],
        [
            "name" => "Caponata",
            "price" => "6.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.hamiciincucina.it/wp-content/uploads/2022/05/caponata_servita2.jpg",
            "description" => "Caponata siciliana di verdure in agrodolce con melanzane fritte, carote, sedano, peperoni, cipolla, olive verdi, pinoli e concentrato di pomodoro",
            "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Parmigiana",
            "price" => "5.0",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.donnamoderna.com/content/uploads/2021/09/parmigiana-di-melanzane.jpg",
            "description" => "Parmigiana con melanzane fritte, salsa di pomodoro, mozzarella, formaggio grattugiato e basilico, servita con ricotta salata",
            "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine antipasti ristorante italiano
        [
            "name" => "Cannelloni Ripieni",
            "price" => "7.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://statics.cucchiaio.it/content/cucchiaio/it/ricette/2020/04/cannelloni-di-carne/jcr:content/header-par/image-single.img10.jpg/1587399398091.jpg",
            "description" => "Cannelloni ripieni di ricotta e cime di rapa, servite con besciamella",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Norma",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.fattoincasadabenedetta.it/wp-content/uploads/2019/08/pasta-alla-norma.jpg",
            "description" => "Rigatoni gratinati con salsa di pomodoro, melanzane fritte, besciamella e ricotta salata",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine primi ristoranti italiani
        [
            "name" => "Burrata Affumicata",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.murgella.it/wp-content/uploads/burratina-affumicata-farcita-con-bietole-aglio-olio-e-peperoncino.jpg",
            "description" => "Burrata affumicata, servita con granella di pistacchio, olio al basilico, pomodorino",
            "type_id" => 4,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Bocconcini di Pollo Cotto a Bassa Temperatura con Crema di Rucola e Mela",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.ricette.com/wp-content/uploads/2016/04/tagliata-di-pollo-con-crema-di-rucola-e-grana-padano1.jpg",
            "description" => null,
            "type_id" => 4,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine secondi ristorante italiano
        [
            "name" => "Patate al forno",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2015/04/patate-al-forno/_jcr_content/header-par/image-single.img.jpg/1581958003248.jpg",
            "description" => null,
            "type_id" => 11,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 6],
        ],
        [
            "name" => "Zucchine al forne",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/allacciateilgrembiule/wp-content/uploads/2020/04/zucchine-al-forno.jpg",
            "description" => null,
            "type_id" => 11,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine contorni ristorante italiano
        [
            "name" => "Insalata Cesarina",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://media-cdn.tripadvisor.com/media/photo-s/11/0e/6c/6b/insalata-cesarina.jpg",
            "description" => "Insalata, pollo cotto a bassa temperatura, pomodori, salsa affumicata, cappuccino di senape e crostini",
            "type_id" => 12,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        [
            "name" => "Insalata Armonia",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.ristorantedong.it/wp-content/uploads/Ristorante-Dong-Menu-WEB-119.jpg",
            "description" => "Insalata, salmone affumicato, bocconcini di bufala, carote allo zenzero, crema di rucola e crostini",
            "type_id" => 12,
            // "menu_id" => null,
            "restaurant_id" => [1],
        ],
        // fine insalate ristorante italiano
        [
            "name" => "Babà alla Crema",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://biancolievito.it/wp-content/uploads/2019/05/fullsizeoutput_30ec-1_eba1po-e1558272820245.jpg",
            "description" => "Babà della tradizione napoletana, con bagna agli agrumi e rum, farcito con crema pasticcera e granella di mandorle",
            "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => [10],
        ],
        [
            "name" => "Cannolo",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.marchesecannoli.it/wp-content/uploads/2019/12/storia-del-cannolo-siciliano.jpg",
            "description" => "Crema di ricotta di pecora, gocce di cioccolato e canditi",
            "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => [10],
        ],
        [
            "name" => "Banana Split",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://static.fanpage.it/wp-content/uploads/sites/21/2022/07/Banana-split.jpg",
            "description" => "Banana fresca, panna montata, topping cioccolato homemade e granella mix frutta secca",
            "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => [10],
        ],
        [
            "name" => "Tiramisù",
            "price" => "5.0",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.giallozafferano.it/images/173-17354/Tiramisu_650x433_wm.jpg",
            "description" => "Caffè , savoiardi, mascarpone, panna, cacao in polvere",
            "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => [10],
        ],
        // fine dolci ristorante italiano
        [
            "name" => "Patatine fritte",
            "price" => "3.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.giallozafferano.it/images/166-16605/Patate-fritte_780x520_wm.jpg",
            "description" => null,
            "type_id" => 10,
            // "menu_id" => null,
            "restaurant_id" => [1, 3, 4, 7, 9],
        ],

        [
            "name" => "Fiore di zucca ripieno",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.buttalapasta.it/wp-content/uploads/2014/05/fiori-di-zucca-ripieni.jpg",
            "description" => "Ripienodi ricotta",
            "type_id" => 10,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],

        [
            "name" => "Calamari fritti",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tavolartegusto.it/wp/wp-content/uploads/2022/05/calamari-fritti-.jpg",
            "description" => null,
            "type_id" => 10,
            // "menu_id" => null,
            "restaurant_id" => [3],
        ],
        // fine frittuta ristoranti generali
        [
            "name" => "Focaccia al crudo",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://citterio.com/uploads/images/ricette/focaccia-romana-crudo.jpg",
            "description" => "Prosciutto crudo, pomodoro fresco, mozzarella di bufala e rucola",
            "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],

        [
            "name" => "Focaccia Ortolana",
            "price" => "7.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/cucinafacilesemplice/wp-content/uploads/2017/05/schiacciata-allortolana-2.jpg",
            "description" => "Verdure grigliate",
            "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],

        [
            "name" => "Focaccia Primavera",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.unafamigliaincucina.com/wp-content/uploads/2021/08/FullSizeRender-3-scaled.jpg",
            "description" => "Pomodoro fresco, tonno, rucola e mais",
            "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => [1, 3],
        ],

        // fine focacce
        [
            "name" => "Panino Sombrero",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.salepepe.it/files/2017/05/panino.jpg",
            "description" => "Prosciutto crudo di Parma 18 mesi, pane con farina 00 lievitato 24h, brie del lodigiano Dop, rucola, pomodoro, crema di tartufo e granella di noci",
            "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => [12],
        ],
        [
            "name" => "Panino Animalier",
            "price" => "10.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://media-assets.vanityfair.it/photos/63735cf7225c55c8c6e2e92e/master/pass/panino%20mortadella.jpg",
            "description" => "Capocollo al malvasia, pane integrale ai farri antichi, zucchine grigliate, bombetta calabra, crema di parmigiano reggiano dop, granella di mandorle e basilico",
            "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => [12],
        ],
        [
            "name" => "Panino Smoking",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cottoecrudo.it/wp-content/uploads/2021/06/panino-866x1300.jpg",
            "description" => "Pulled pork, focaccia all’alga spirulina, cavolo cappuccio viola, stracchino, marmellata di peperoni, maionese della casa e granella di pistacchio",
            "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => [12],
        ],
        // fine panini
        [
            "name" => "Macedonia",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://dolciveloci.it/wp-content/uploads/2019/06/SH_macedonia.jpg",
            "description" => "Mela , pera , banana, fragole, sciroppo di arancia, sciroppo di limone, zucchero",
            "type_id" => 16,
            // "menu_id" => null,
            "restaurant_id" => [10],
        ],
        // fine frutta
        [
            "name" => "Piatto Kebab",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://thumbs.dreamstime.com/z/piatto-degli-alimenti-rapida-preparazione-di-kebab-22677562.jpg",
            "description" => "Kebab di pollo 100% italiano, pomodori, cipolla, lattuga, salsa yogurt, salsa piccante.",
            "type_id" => 17,
            // "menu_id" => null,
            "restaurant_id" => [9, 8],
        ],

        // fine kebab
        [
            "name" => "Nigiri Salmone",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "http://cdn.cook.stbm.it/thumbnails/ricette/144/144483/hd750x421.jpg",
            "description" => "3 pezzi - riso e salmone",
            "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => [2, 6],
        ],

        [
            "name" => "California Roll",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2018/05/1467Mod.jpg",
            "description" => "9 pezzi - roll di surimi, avocado, cetriolo e sesamo",
            "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => [2, 6],
        ],

        [
            "name" => "Futomaki Salmone Affumicato",
            "price" => "5.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.irorisushiathome.it/wp-content/uploads/2020/08/uramaki_2_spicy_ebi2.jpg",
            "description" => "5 pezzi - riso, alga, mix di salmone e formaggio spalmabile, avocado, cetriolo e carota",
            "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => [2, 6],
        ],

        [
            "name" => "Gunkan Spicy Ebi e Avocado",
            "price" => "6.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.sushimaisoncrema2.it/wp-content/uploads/2020/04/037-Sushi-Maison-Crema-2.jpg",
            "description" => "3 pezzi - riso, tartare di mazzancolla tropicale, avocado, spicy mayo e zucchina",
            "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => [6],
        ],
        [
            "name" => "Ebi in Tempura Crunch Roll",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://media.istockphoto.com/id/183815946/photo/shrimp-tempura-roll.jpg?s=612x612&w=0&k=20&c=a-WZduJWWdTBdJqFB22HJadz7oasGNsc-3YyemfBtu8=",
            "description" => "9 pezzi - roll di gamberi in tempura con avocado, cetriolo, ricoperto con mayo piccante, salsa unagi e cipolla fritta croccante",
            "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => [6],
        ],
        // fine sushi
        [
            "name" => "Panino ca Mieusa",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://bbq4all.it/wp-content/uploads/2017/04/GIO8721.jpg",
            "description" => "Milza, limone, grana",
            "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => [12],
        ],
        [
            "name" => "Hamburger Top",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger.jpg",
            "description" => "Hamburger, formaggio, pomodoro e insalata",
            "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => [4, 12],
        ],

        [
            "name" => "Toast Americano",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.spignattando.it/wp-content/uploads/2017/10/toast-al-formaggio-940x627.jpg",
            "description" => "maxi toast con prosciutto cotto e fontina",
            "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => [7],
        ],
        // fine street food
        [
            "name" => "Koshari Grande",
            "price" => "10.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://c8.alamy.com/compit/etffk3/kushari-koshari-cibo-egiziano-isolati-su-sfondo-bianco-etffk3.jpg",
            "description" => "Cipolle croccanti, ceci, salsa al pomodoro, pasta filini lenticchie, ditaloni rigati e riso bianco",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [4],
        ],
        [
            "name" => "Koshari 101",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.fondazioneveronesi.it/uploads/2017/05/15/thinkstockphotos-624024462.jpg",
            "description" => "cipolle croccanti, ceci, salsa al pomodoro, pasta filini lenticchie, ditaloni rigati e riso bianco",
            "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => [4],
        ],
        // fine koshari per ristorante egiziano
        [
            "name" => "El Dorado",
            "price" => "12.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.hynerd.it/wp-content/uploads/2022/01/el-dorado-film-1920x1080-1.jpg",
            "description" => "Tinga di pollo, crema di fagioli, cavolo rosso alla Britos, pico de gallo e salsa a scelta",
            "type_id" => 23,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        [
            "name" => "Reynosa",
            "price" => "12.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://media-cdn.tripadvisor.com/media/photo-s/1b/a6/75/88/quesadillas-varias.jpg",
            "description" => "Tinga di pollo vegano, peperoncino jalapeÃ±o, cavolo rosso alla Britos, cipolle grigliate, pico de gallo e salsa a scelta",
            "type_id" => 23,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        // fine tacos per messicano
        [
            "name" => "Houston",
            "price" => "14.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://bakeitwithlove.com/wp-content/uploads/2020/12/Leftover-Prime-Rib-Burritos-lg.jpg",
            "description" => "Pulled pork, riso alla messicana, fagioli neri alla messicana, pico de frutta, formaggio ranchero, peperoncino jalapenoe salsa piccante",
            "type_id" => 24,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        [
            "name" => "La Cruz",
            "price" => "14.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/2021-09/Burrito%20messicano%20-%20Fine%20Dining%20Lovers.jpg",
            "description" => "Tinga di pollo vegano, riso alla messicana, crema di fagioli, pico de gallo, cipolle grigliate, insalata iceberg e salsa piccante",
            "type_id" => 24,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        // fine burritos per messicano
        [
            "name" => "Cornetto Ischitano Vuoto",
            "price" => "2.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://blog.giallozafferano.it/elisapassione/wp-content/uploads/2020/12/DSC_0031-scaled.jpg",
            "description" => null,
            "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        [
            "name" => "Pasticciotto alla Crema e Amarena",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://primochef.it/wp-content/uploads/2019/04/SH_pasticciotto-1200x800.jpg",
            "description" => null,
            "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        [
            "name" => "Fagottino alla Marmellata",
            "price" => "1.80",
            "available" => '1',
            "discount" => null,
            "image" => "https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/09/1474269568_8908daab6a388641c7af950d6b9d6bb7698aeb4e-1472887501.jpg",
            "description" => null,
            "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => [13],
        ],
        // fine colazione
        [
            "name" => "Acqua Naturale",
            "price" => "1.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.colizzivini.it/media/catalog/product/cache/a2269601488aaf6aadf9012f10675769/a/c/acqua-daggio-naturale-norda-cl-50-pet.webp",
            "description" => "50 cl",
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        ],

        [
            "name" => "Acqua Frizzante",
            "price" => "1.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.colizzivini.it/media/catalog/product/cache/a2269601488aaf6aadf9012f10675769/a/c/acqua-daggio-naturale-norda-cl-50-pet.webp",
            "description" => "50 cl",
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        ],

        [
            "name" => "Coca Cola",
            "price" => "1.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.tsunaminutrition.it/12278-large_default/coca-cola-zero-lattina-330-ml.jpg",
            "description" => "33 cl",
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        ],

        [
            "id" => 109,
            "name" => "Coca Cola Zero",
            "price" => "1.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://www.bamboo-bz.it/wp-content/uploads/2020/05/cola-zero.jpg",
            "description" => "33 cl",
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        ],

        [
            "id" => 111,
            "name" => "Crodino",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://e8v9k5qwo6b.exactdn.com/wp-content/uploads/2021/06/PF011.jpg?strip=all&lossy=1&w=2560&ssl=1",
            "description" => null,
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6],
        ],
        [
            "id" => 112,
            "name" => "Birra",
            "price" => "2.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://objectstorage.eu-milan-1.oraclecloud.com/n/axl3hgtiszxy/b/Bucket-CRAI-IMG-PROD/o/images/catalog/eg-0011751/eg-0011751_1_big.jpg",
            "description" => "66 cl",
            "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
        ],

        // fine bevande




    ],
    'users' => [
        [
            'name' => 'Pippo',
            'lastname' => 'Mustica',
            'password' => 'deliveboo',
            'email' => 'pippo.mustica@gmail.com'
        ],
        [
            'name' => 'Herbert',
            'lastname' => 'Fonzarelli',
            'password' => 'deliveboo',
            'email' => 'herbert.fonzarelli@gmail.com'
        ],
        [
            'name' => 'Melo',
            'lastname' => 'Fonte',
            'password' => 'deliveboo',
            'email' => 'melo.fonte@gmail.com'
        ],
        [
            'name' => 'Gino',
            'lastname' => 'Fantozzi',
            'password' => 'deliveboo',
            'email' => 'gino.fantozzi@gmail.com'
        ],
        [
            'name' => 'Simone',
            'lastname' => 'Gallo',
            'password' => 'deliveboo',
            'email' => 'simone.gallo@gmail.com'
        ],
        [
            'name' => 'Giuseppe',
            'lastname' => 'Ferro',
            'password' => 'deliveboo',
            'email' => 'giuseppe.ferro@gmail.com'
        ],
        [
            'name' => 'Ricco',
            'lastname' => 'Galluzzo',
            'password' => 'deliveboo',
            'email' => 'ricco.galluzzo@gmail.com'
        ],
        [
            'name' => 'Riccardo',
            'lastname' => 'Palazzi',
            'password' => 'deliveboo',
            'email' => 'riccardo.palazzi@gmail.com'
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Marino',
            'password' => 'deliveboo',
            'email' => 'michele.marino@gmail.com'
        ],
        [
            'name' => 'Basilio',
            'lastname' => 'Matassa',
            'password' => 'deliveboo',
            'email' => 'basilio.matassa@gmail.com'
        ],
        [
            'name' => 'Chin',
            'lastname' => 'Chao',
            'password' => 'deliveboo',
            'email' => 'chin.chao@gmail.com'
        ],
        [
            'name' => 'Paninaro',
            'lastname' => 'Difiducia',
            'password' => 'deliveboo',
            'email' => 'paninaro.difiducia@gmail.com'
        ],
        [
            'name' => 'Speedy',
            'lastname' => 'Gonzales',
            'password' => 'deliveboo',
            'email' => 'speedy.gonzales@gmail.com'
        ],
        [
            'name' => 'Mario',
            'lastname' => 'Rossi',
            'password' => 'deliveboo',
            'email' => 'mario.rossi@gmail.com'
        ],
            
        [
            'name' => 'Giulia',
            'lastname' => 'Verdi',
            'password' => 'deliveboo',
            'email' => 'giulia.verdi@gmail.com'
        ],
            
        [
            'name' => 'Luca',
            'lastname' => 'Bianchi',
            'password' => 'deliveboo',
            'email' => 'luca.bianchi@gmail.com'
        ],
            
        [
            'name' => 'Federica',
            'lastname' => 'Neri',
            'password' => 'deliveboo',
            'email' => 'federica.neri@gmail.com'
        ],
            
        [
            'name' => 'Alessandro',
            'lastname' => 'Russo',
            'password' => 'deliveboo',
            'email' => 'alessandro.russo@gmail.com'
        ],
            
        [
            'name' => 'Valentina',
            'lastname' => 'Grasso',
            'password' => 'deliveboo',
            'email' => 'valentina.grasso@gmail.com'
        ],
        [
            'name' => 'Marco',
            'lastname' => 'Pellegrini',
            'password' => 'deliveboo',
            'email' => 'marco.pellegrini@gmail.com'
        ],
            
        [
            'name' => 'Martina',
            'lastname' => 'Mancini',
            'password' => 'deliveboo',
            'email' => 'martina.mancini@gmail.com'
        ],
            
        [
            'name' => 'Giacomo',
            'lastname' => 'Fontana',
            'password' => 'deliveboo',
            'email' => 'giacomo.fontana@gmail.com'
        ],
            
        [
            'name' => 'Sara',
            'lastname' => 'Fabbri',
            'password' => 'deliveboo',
            'email' => 'sara.fabbri@gmail.com'
        ],
            
        [
            'name' => 'Davide',
            'lastname' => 'Conti',
            'password' => 'deliveboo',
            'email' => 'davide.conti@gmail.com'
        ],
            
        [
            'name' => 'Chiara',
            'lastname' => 'Lombardi',
            'password' => 'deliveboo',
            'email' => 'chiara.lombardi@gmail.com'
        ],
            
        [
            'name' => 'Roberto',
            'lastname' => 'Galli',
            'password' => 'deliveboo',
            'email' => 'roberto.galli@gmail.com'
        ],
            
        [
            'name' => 'Elisa',
            'lastname' => 'Ferrari',
            'password' => 'deliveboo',
            'email' => 'elisa.ferrari@gmail.com'
        ],
            
        [
            'name' => 'Andrea',
            'lastname' => 'Greco',
            'password' => 'deliveboo',
            'email' => 'andrea.greco@gmail.com'
        ],
        [
            'name' => 'Andrea',
            'lastname' => 'Friarello',
            'password' => 'deliveboo',
            'email' => 'andrea.friarello@gmail.com'
        ],
        [
            'name' => 'Carlo',
            'lastname' => 'Greco',
            'password' => 'deliveboo',
            'email' => 'carlo.greco@gmail.com'
        ]
    ],
    'restaurants' => [

        [
            "id" => 1,
            "user_id" => 1,
            "restaurant_name" => "Gusto Italiano",
            "address" => "Via del Corso, 00186 Roma",
            "p_iva" => "92255625968",
            "contact_phone" => "3774362879",
            "image" => "https://burst.shopifycdn.com/photos/open-kitchen-restaurant.jpg?width=925&format=pjpg&exif=1&iptc=1",
            "description" => "Pizza·Italiano·Vegano·Gourmet",
            "delivery_price" => 2,
            "opening_time" => "12:00",
            "closing_time" => "22:45",
            "min_price_order" => 15,
            // "product_id" => null,
            "category_id" => [2, 3, 14, 17],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 2,
            "user_id" => 2,
            "restaurant_name" => "La Piazza",
            "address" => "Piazza Navona, 00186 Roma",
            "p_iva" => "36749577791",
            "contact_phone" => "6416659176",
            "image" => "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Pizzeria_in_Venice.jpg/1200px-Pizzeria_in_Venice.jpg",
            "description" => "Pizza·Kebab·Focacce·Fritti",
            "delivery_price" => null,
            "opening_time" => "08:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [2 ,4, 6, 13, 14],
            // "customer_order_id" => null,
            "rating" => 2,
        ],
        [
            "id" => 3,
            "user_id" => 3,
            "restaurant_name" => "Il Cibo Felice",
            "address" => "Via dei Condotti, 00187 Roma",
            "p_iva" => "79554564471",
            "contact_phone" => "5478185546",
            "image" => "https://burst.shopifycdn.com/photos/picturesque-restaurant-under-fairy-lights.jpg?width=925&format=pjpg&exif=1&iptc=1",
            "description" => "Italiano·Giapponese",
            "delivery_price" => 2,
            "opening_time" => "18:00",
            "closing_time" => "24:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [3, 6],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 4,
            "user_id" => 4,
            "restaurant_name" => "Trattoria del Borgo",
            "address" => "Piazza di Spagna, 00187 Roma",
            "p_iva" => "32661682277",
            "contact_phone" => "1784627673",
            "image" => "https://c8.alamy.com/zoomsit/9/3f820adaf8414f159273f5d43fb58740/b5ar0y.jpg",
            "description" => "Hamburger, Egiziano",
            "delivery_price" => 2.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [2, 3],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 5,
            "user_id" => 5,
            "restaurant_name" => "H x H",
            // africano, fa insalate e piadine
            "address" => "Via Veneto, 00187 Roma",
            "p_iva" => "37221289354",
            "contact_phone" => "2547438929",
            "image" => "https://burst.shopifycdn.com/photos/person-sits-alone-by-the-window-of-a-quiet-restaurant.jpg?width=925&format=pjpg&exif=1&iptc=1",
            "description" => "Giapponese, Sushi",
            "delivery_price" => 2,
            "opening_time" => "10:00",
            "closing_time" => "22:15",
            "min_price_order" => 10,
            // "product_id" => null,
            "category_id" => [6],
            // "customer_order_id" => null,
            "rating" => 5,
        ],
        [
            "id" => 6,
            "user_id" => 6,
            "restaurant_name" => "Ichiraku Ramen",
            // Giapponese
            "address" => "Piazza del Popolo, 00187 Roma",
            "p_iva" => "33724782362",
            "contact_phone" => "2785587994",
            "image" => "https://images.unsplash.com/photo-1508006728353-6ecef00dcbb8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80",
            "description" => "Vantiamo come nostro migliore cliente Naruto Uzumaki, settimo hokage del villaggio della foglia",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "24:00",
            "min_price_order" => 10,
            // "product_id" => null,
            "category_id" => [6],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 7,
            "user_id" => 7,
            "restaurant_name" => "Grande Muraglia",
            "address" => "Via della Conciliazione, 00193 Roma",
            "p_iva" => "74841879582",
            "contact_phone" => "9618229127",
            "image" => "https://images.unsplash.com/photo-1591214896508-22fc74d84a75?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Stai cercando Hamburger e Dolci a domicilio? Con Sweetburger di Milano non hai più bisogno di cercare. Vai al suo menù su Just Eat e fai il tuo ordine ora.",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 10,
            // "product_id" => null,
            "category_id" => [1],
            // "customer_order_id" => null,
            "rating" => 2,
        ],
        [
            "id" => 8,
            "user_id" => 8,
            "restaurant_name" => "Haidilao Hot Pot",
            // hamburger ma senza glutine!!!!!!!!!!!!!
            "address" => "Piazza San Pietro, 00120 Città del Vaticano",
            "p_iva" => "46644626375",
            "contact_phone" => "2377227849",
            "image" => "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Voglia di Hamburger ma quella di cucinare è scappata di casa? Non temere!",
            "delivery_price" => 1,
            "opening_time" => "10:00",
            "closing_time" => "23:59",
            "min_price_order" => 7.50,
            // "product_id" => null,
            "category_id" => [1],
            // "customer_order_id" => null,
            "rating" => 5,
        ],
        [
            "id" => 9,
            "user_id" => 9,
            "restaurant_name" => "Istanbul Kebab",
            // pizza kebab
            "address" => "Via dei Fori Imperiali, 00186 Roma",
            "p_iva" => "83853142392",
            "contact_phone" => "9677759339",
            "image" => "https://images.unsplash.com/photo-1619738566066-81c6d589c80c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Voglia di Pizza e Kebab a domicilio a Milano? Scopri il menu di Istanbul Kebab e ordina comodamente online. Puoi pagare anche con carta di credito!",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:15",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [4],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 10,
            "user_id" => 10,
            "restaurant_name" => "Lezzet Istanbul",
            // dolci bakery
            "address" => "Piazza del Campidoglio, 00186 Roma",
            "p_iva" => "44378213487",
            "contact_phone" => "6457856444",
            "image" => "https://images.unsplash.com/photo-1532636875304-0c89119d9b4d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Stai cercando Dolci e Rosticceria a domicilio? Con Mergellina Bakery® di Milano non hai più bisogno di cercare.",
            "delivery_price" => 2,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [4],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 11,
            "user_id" => 11,
            "restaurant_name" => "Hard Rock Cafe",
            // cinese
            "address" => "Via Nazionale, 00184 Roma",
            "p_iva" => "44378213484",
            "contact_phone" => "7277753942",
            "image" => "https://images.unsplash.com/photo-1534760110157-0ca7f60f159a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1167&q=80",
            "description" => "Ristorante cinese",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [5, 13],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 12,
            "user_id" => 12,
            "restaurant_name" => "Applebee's",
            // cinese
            "address" => "Piazza Venezia, 00186 Roma",
            "p_iva" => "32511215225",
            "contact_phone" => "4731586938",
            "image" => "https://as1.ftcdn.net/v2/jpg/05/68/12/08/1000_F_568120844_3O1ukYctfNYu0IkcvErPM0eUh7bSjRr2.jpg",
            "description" => "Panini e focacce",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [5, 13],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 13,
            "user_id" => 13,
            "restaurant_name" => "T.G.I. Friday's ",
            // cinese
            "address" => "Via Appia Antica, 00178 Roma",
            "p_iva" => "31767897481",
            "contact_phone" => "9262983187",
            "image" => "https://as2.ftcdn.net/v2/jpg/05/33/26/63/1000_F_533266332_1DYvIT5sJEAhky33Wf7hUtZkuplBN9ZI.jpg",
            "description" => "Tacos e burritos",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [5, 13],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 14,
            "user_id" => 14,
            "restaurant_name" => "The Cheesecake Factory",
            // pizza italiano
            "address" => "Via del Babuino, 00187 Roma",
            "p_iva" => "47414425499",
            "contact_phone" => "8517361528",
            "image" => "https://as2.ftcdn.net/v2/jpg/05/44/86/63/1000_F_544866372_IQS9KEK2LT9sj6PbZJYJr9xlvmyxCn8l.jpg",
            "description" => "Pizza·Italiano·Sandwich",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:45",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [5, 9, 13],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 15,
            "user_id" => 15,
            "restaurant_name" => "Ahi Assassins Fish Co.",
            // sushi
            "address" => "Piazza della Repubblica, 00185 Roma",
            "p_iva" => "23821873496",
            "contact_phone" => "1923552133",
            "image" => "https://as2.ftcdn.net/v2/jpg/05/69/46/97/1000_F_569469719_PGLgVfIWHUofDMOqTJG4k18VHYo4n9fc.jpg",
            "description" => "Ristorante di sushi",
            "delivery_price" => null,
            "opening_time" => "10:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [7],
            // "customer_order_id" => null,
            "rating" => 2,
        ],
        [
            "id" => 16,
            "user_id" => 16,
            "restaurant_name" => "Safari Restaurant",
            // pizza fritti
            "address" => "Via della Lungara, 00165 Roma",
            "p_iva" => "12533568283",
            "contact_phone" => "5289836635",
            "image" => "https://as1.ftcdn.net/v2/jpg/01/78/88/26/1000_F_178882641_2fejDjj9yALkp2aNayKJdTKdj12YS7YK.jpg",
            "description" => "Italiano·Pizza",
            "delivery_price" => 2,
            "opening_time" => "12:00",
            "closing_time" => "24:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [8, 9, 11],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 17,
            "user_id" => 17,
            "restaurant_name" => "Meskerem Ethiopian Restaurant",
            // hamburger egiziano
            "address" => "Piazza Trilussa, 00153 Roma",
            "p_iva" => "39694857864",
            "contact_phone" => "1918481349",
            "image" => "https://as2.ftcdn.net/v2/jpg/04/46/02/43/1000_F_446024320_iwtjospA0lI8w0R1pTcnDKmk7bQMqgkW.jpg",
            "description" => "Hamburger, Egiziano",
            "delivery_price" => 2.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [8, 9, 11],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 18,
            "user_id" => 18,
            "restaurant_name" => "Peli Peli",
            // africano, fa insalate e piadine
            "address" => "Via dei Serpenti, 00184 Roma",
            "p_iva" => "75114196343",
            "contact_phone" => "6348725247",
            "image" => "https://as1.ftcdn.net/v2/jpg/03/24/73/92/1000_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg",
            "description" => "Africano·Insalate·Piadina",
            "delivery_price" => 2,
            "opening_time" => "10:00",
            "closing_time" => "22:15",
            "min_price_order" => 15,
            // "product_id" => null,
            "category_id" => [8, 9, 11],
            // "customer_order_id" => null,
            "rating" => 5,
        ],
        [
            "id" => 19,
            "user_id" => 19,
            "restaurant_name" => "Greenway - Vegan Street Food",
            // Giapponese
            "address" => "Piazza del Pantheon, 00186 Roma",
            "p_iva" => "31838621799",
            "contact_phone" => "2854186717",
            "image" => "https://images.unsplash.com/photo-1544031064-9de80864ade5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
            "description" => "Stai cercando Uramaki, burritos e sushi nippo-brasiliano a domicilio? Con Bomaki - Garibaldi di Milano non hai più bisogno di cercare.",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "24:00",
            "min_price_order" => 15,
            // "product_id" => null,
            "category_id" => [10, 16, 17],
            // "customer_order_id" => null,
            "rating" => 2,
        ],
        [
            "id" => 20,
            "user_id" => 20,
            "restaurant_name" => "The Butcher's Daughter",
            // americano hamburger
            "address" => "Lungotevere Castello, 00193 Roma",
            "p_iva" => "24273299323",
            "contact_phone" => "4582445736",
            "image" => "https://images.unsplash.com/photo-1453614512568-c4024d13c247?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1632&q=80",
            "description" => "Stai cercando Hamburger e Dolci a domicilio? Con Sweetburger di Milano non hai più bisogno di cercare. Vai al suo menù su Just Eat e fai il tuo ordine ora.",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 10,
            // "product_id" => null,
            "category_id" => [10, 16, 17],
            // "customer_order_id" => null,
            "rating" => 2,
        ],
        [
            "id" => 21,
            "user_id" => 21,
            "restaurant_name" => "La Capra Campa",
            // hamburger ma senza glutine!!!!!!!!!!!!!
            "address" => "Piazza Barberini, 00187 Roma",
            "p_iva" => "65464684934",
            "contact_phone" => "1257941853",
            "image" => "https://images.unsplash.com/photo-1464979681340-bdd28a61699e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Voglia di Hamburger ma quella di cucinare è scappata di casa? Non temere!",
            "delivery_price" => 1,
            "opening_time" => "10:00",
            "closing_time" => "23:59",
            "min_price_order" => 7.50,
            // "product_id" => null,
            "category_id" => [10, 16, 17],
            // "customer_order_id" => null,
            "rating" => 5,
        ],
        [
            "id" => 22,
            "user_id" => 22,
            "restaurant_name" => "Magnolia Bakery",
            // pizza kebab
            "address" => "Via del Tritone, 00187 Roma",
            "p_iva" => "18318228932",
            "contact_phone" => "1955786311",
            "image" => "https://as2.ftcdn.net/v2/jpg/05/66/06/17/1000_F_566061758_UiZdNnM7vhbzwYEotpRe0vGLPK8iQzKp.jpg",
            "description" => "Voglia di Pizza e Kebab a domicilio a Milano? Scopri il menu di Istanbul Kebab e ordina comodamente online. Puoi pagare anche con carta di credito!",
            "delivery_price" => 2,
            "opening_time" => "12:00",
            "closing_time" => "22:15",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [10, 16],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 23,
            "user_id" => 23,
            "restaurant_name" => "Ladurée",
            // dolci bakery
            "address" => "Piazza di Santa Maria in Trastevere, 00153 Roma",
            "p_iva" => "16953175614",
            "contact_phone" => "1951986229",
            "image" => "https://as2.ftcdn.net/v2/jpg/02/95/78/71/1000_F_295787159_WTME560tqmWJkSvUDfGllwZYop4GJv7f.jpg",
            "description" => "Stai cercando Dolci e Rosticceria a domicilio? Con Mergellina Bakery® di Milano non hai più bisogno di cercare.",
            "delivery_price" => 2,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [10, 16],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 24,
            "user_id" => 24,
            "restaurant_name" => "Carlo's Bakery",
            // cinese
            "address" => "Via del Governo Vecchio, 00186 Roma",
            "p_iva" => "79651849161",
            "contact_phone" => "9521297589",
            "image" => "https://as1.ftcdn.net/v2/jpg/04/97/97/14/1000_F_497971444_7aiyjHhU0dFJvJOPhgXCmXzKysYU0APv.jpg",
            "description" => "Ristorante cinese",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [10, 16],
            // "customer_order_id" => null,
            "rating" => 3,
        ],
        [
            "id" => 25,
            "user_id" => 25,
            "restaurant_name" => "El Nopal Mexican Cuisine",
            // cinese
            "address" => "Piazza della Rotonda, 00186 Roma",
            "p_iva" => "15536519961",
            "contact_phone" => "2626632676",
            "image" => "https://as1.ftcdn.net/v2/jpg/01/12/26/70/1000_F_112267066_HiNvJ0psmNuxQme1QfpYs3oG3K6Fithq.jpg",
            "description" => "Panini e focacce",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            "category_id" => [12],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 26,
            "user_id" => 26,
            "restaurant_name" => "La Cantina del Vino",
            // cinese
            "address" => "Via Margutta, 00187 Roma",
            "p_iva" => "41329644841",
            "contact_phone" => "9148527196",
            "image" => "https://www.consorziodelroero.it/wp-content/uploads/2019/10/botti_legno_vino2-1014x487.jpg",
            "description" => "ATTENZI0NE, qui si mangia tanto ma si beve di più. Spesa minima 50 euro in vino",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [3],
            // "customer_order_id" => null,
            "rating" => 5,
        ],
        [
            "id" => 27,
            "user_id" => 27,
            "restaurant_name" => "La Taqueria",
            // cinese
            "address" => "Piazza Farnese, 00186 Roma",
            "p_iva" => "85227572184",
            "contact_phone" => "2694384822",
            "image" => "https://images.unsplash.com/photo-1483648969698-5e7dcaa3444f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            "description" => "Tacos e burritos",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [12],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 28,
            "user_id" => 28,
            "restaurant_name" => "Taquería Los Parados",
            // cinese
            "address" => "Via dei Coronari, 00186 Roma",
            "p_iva" => "69885373235",
            "contact_phone" => "6339476565",
            "image" => "https://plus.unsplash.com/premium_photo-1664475361087-e2bea16ee3bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
            "description" => "Tacos e burritos",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [12],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 29,
            "user_id" => 29,
            "restaurant_name" => "Il Forno di Pietra - Pizza Gourmet",
            // cinese
            "address" => "Piazza Santa Maria Maggiore, 00185 Roma",
            "p_iva" => "27197918558",
            "contact_phone" => "5199929939",
            "image" => "https://images.unsplash.com/photo-1421622548261-c45bfe178854?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
            "description" => "Tacos e burritos",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [2,15],
            // "customer_order_id" => null,
            "rating" => 4,
        ],
        [
            "id" => 30,
            "user_id" => 30,
            "restaurant_name" => "La Cantina degli Amici",
            // cinese
            "address" => "Via del Pellegrino, 00186 Roma",
            "p_iva" => "78394879451",
            "contact_phone" => "7817643916",
            "image" => "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            "description" => "Tacos e burritos",
            "delivery_price" => 1.50,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => 5,
            // "product_id" => null,
            "category_id" => [2],
            // "customer_order_id" => null,
            "rating" => 4,
        ]

    ]
];
