<?php

return [
    "categories" => [
        [
            "name" => "Cinese",
            // 0
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Pizza",
            // 1
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Italiano",
            // 2
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Kebab",
            // 3
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Americano",
            // 4
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Giapponese",
            // 5
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Poke",
            // 6
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Africano",
            // 7
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Arabo",
            // 8
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Bakery",
            // 9
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Egiziano",
            // 10
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Messicano",
            // 11
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Focacce",
            // 12
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Fritti",
            // 13
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Gourmet",
            // 14
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Colazione",
            // 15
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ],
        [
            "name" => "Vegano",
            // 16
            "image" => "https://www.papido.it/gallery/imageHD.php?src=/roma/upload/70918601-2090036047768528-2020200947858276352-n-53834.jpg&w=600"
        ]

    ],
    "ingredients" => [
        'Pomodoro san marzano dop',
        'Mozzarella fiordilatte',
        'Olio extravergine',
        'Funghi',
        'Prosciutto cotto',
        'Prosciutto crudo',
        'Mortadella',
        'Salsiccia',
        'Rucola',
        'Pomodorini',
        'Melanzane',
        'Peperoni',
        'Zucchine',
        'Bresaola',
        'Speck',
        'Wurstel',
        'Olive',
        'Scamorza',
        'Mozzarella di bufala',
        'Cipolla'
    ],
    'types' => [
        'Colazione',
        // 0
        'Antipasti',
        // 1
        'Primi piatti',
        // 2
        'Secondi',
        // 3
        'Carne',
        // 4
        'Pesce',
        // 5
        'Desserts',
        // 6
        'Bevande',
        // 7
        'Pizze',
        // 8
        'Fritti',
        // 9
        'Contorni',
        // 10
        'Insalate',
        // 11
        'Focacce',
        // 12
        'Hamburgers',
        // 13
        'Panini',
        // 14
        'Frutta',
        // 15
        'Kebab',
        // 16 per kabbabbaro
        'Zuppe',
        // 17 per africani-giapponesi-cinesi
        'Sushi',
        // 18 per giapponesi
        'Gyoza',
        // 19 per cinesi-giapponesi
        'Street Food',
        // 20
        'Koshari',
        // 21 per egiziano
        'Tacos',
        // 22 per messicano
        'Burritos' // 23 per messicano

    ],
    'products' => [

        [
            "id" => 1,
            "name" => "Zuppa di Miso",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Zuppa di verdure a base di fagioli di soia",
            "type" => null,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 2,
            "name" => "Zuppa con Pollo e Mais",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Zuppa cpn uovo, pollo e mais",
            "type" => null,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 3,
            "name" => "Zuppa di Miso",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Zuppa di verdure a base di fagioli di soia",
            "type" => null,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 4,
            "name" => "Zuppa con Pollo e Mais",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Zuppa cpn uovo, pollo e mais",
            "type" => null,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine zuppe ristorante cinese
        [
            "id" => 5,
            "name" => "Gnocchi di Riso con Gamberi e Verdure",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 6,
            "name" => "Spaghetti di Soia con Carne e Verdure",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 7,
            "name" => "Gnocchi di Riso con Gamberi e Verdure",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 8,
            "name" => "Spaghetti di Soia con Carne e Verdure",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine primi ristorante cinese
        [
            "id" => 9,
            "name" => "Involtino Primavera",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Involtino fritto ripieno di verdure",
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 10,
            "name" => "Tofu Crudo",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Preparazione a base di soia condita con salsa cinese",
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine antipasto cinese
        [
            "id" => 11,
            "name" => "Yasai Gyoza",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Ravioli vegetariani",
            // "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 12,
            "name" => "Ebi Gyoza",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Ravioli giapponesi con ripieno di gamberi",
            // "type_id" => 19,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine gyoza cinese
        [
            "id" => 13,
            "name" => "Santa Cruz Wrap",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Tortilla di grano farcita con petto di pollo speziato, leggermente piccante, lattuga, formaggio fuso e salsa Cheddar.",
            // "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 14,
            "name" => "Cheeseburger",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Hamburger di scottona, formaggio cheddar, cetrioli fatti in casa e salsa ketchup racchiusi in un morbido bun artigianale",
            // "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 15,
            "name" => "Gran Crispy Clover",
            "price" => "13.20",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Doppio hamburger di scottona, doppio formaggio cheddar, doppio bacon e doppio strato di salsa Clover crispy racchiusi in un morbido bun artigianale",
            // "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 16,
            "name" => "American Burger",
            "price" => "10.80",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Hamburger di scottona, insalata iceberg, formaggio cheddar, bacon, pomodoro fresco, la nostra cipolla caramellata e salsa BBQ racchiusi in un morbido bun artigianale",
            // "type_id" => 13,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine hamburger
        [
            "id" => 17,
            "name" => "Marinara",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Pomodoro San Marzano DOP, aglio, origano, olio evo della Penisola Sorrentina DOP e basilico",
            // "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 18,
            "name" => "Margherita",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588869",
            "description" => "Pomodoro e mozzarella",
            // "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 19,
            "name" => "Battipagliese",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Datterino giallo di Battipaglia, provola affumicata, olive e capperi, basilico e peperoncino",
            // "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 20,
            "name" => "Bianca, cotto e funghi",
            "price" => "10.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Mozzarella, fior di panna, funghi champignon, prosciutto cotto Fiorucci, basilico",
            // "type_id" => 8,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine pizze
        [
            "id" => 21,
            "name" => "Bruschetta alla 'Nduja",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Bruschetta con 'nduja calabrese, stracciatella fresca e olio al basilico",
            // "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 22,
            "name" => "Caponata",
            "price" => "6.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Caponata siciliana di verdure in agrodolce con melanzane fritte, carote, sedano, peperoni, cipolla, olive verdi, pinoli e concentrato di pomodoro",
            // "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 23,
            "name" => "Parmigiana",
            "price" => "5.0",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Parmigiana con melanzane fritte, salsa di pomodoro, mozzarella, formaggio grattugiato e basilico, servita con ricotta salata",
            // "type_id" => 1,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine antipasti ristorante italiano
        [
            "id" => 24,
            "name" => "Cannelloni Ripieni",
            "price" => "7.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Cannelloni ripieni di ricotta e cime di rapa, servite con besciamella",
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 25,
            "name" => "Norma",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Rigatoni gratinati con salsa di pomodoro, melanzane fritte, besciamella e ricotta salata",
            // "type_id" => 2,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine primi ristoranti italiani
        [
            "id" => 26,
            "name" => "Burrata Affumicata",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Burrata affumicata, servita con granella di pistacchio, olio al basilico, pomodorino",
            // "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 27,
            "name" => "Bocconcini di Pollo Cotto a Bassa Temperatura con Crema di Rucola e Mela",
            "price" => "7.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 3,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine secondi ristorante italiano
        [
            "id" => 28,
            "name" => "Patate al forno",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 10,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 29,
            "name" => "Zucchine al forne",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 10,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine contorni ristorante italiano
        [
            "id" => 30,
            "name" => "Insalata Cesarina",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Insalata, pollo cotto a bassa temperatura, pomodori, salsa affumicata, cappuccino di senape e crostini",
            // "type_id" => 11,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 31,
            "name" => "Insalata Armonia",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Insalata, salmone affumicato, bocconcini di bufala, carote allo zenzero, crema di rucola e crostini",
            // "type_id" => 11,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine insalate ristorante italiano
        [
            "id" => 32,
            "name" => "Babà alla Crema",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Babà della tradizione napoletana, con bagna agli agrumi e rum, farcito con crema pasticcera e granella di mandorle",
            // "type_id" => 6,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 33,
            "name" => "Cannolo",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Crema di ricotta di pecora, gocce di cioccolato e canditi",
            // "type_id" => 6,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 34,
            "name" => "Banana Split",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Banana fresca, panna montata, topping cioccolato homemade e granella mix frutta secca",
            // "type_id" => 6,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 35,
            "name" => "Tiramisù",
            "price" => "5.0",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Caffè , savoiardi, mascarpone, panna, cacao in polvere",
            // "type_id" => 6,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine dolci ristorante italiano
        [
            "id" => 36,
            "name" => "Patatine fritte",
            "price" => "3.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 37,
            "name" => "Fiore di zucca ripieno",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Ripienodi ricotta",
            // "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 38,
            "name" => "Calamari fritti",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 9,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine frittuta ristoranti generali
        [
            "id" => 39,
            "name" => "Focaccia al crudo",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Prosciutto crudo, pomodoro fresco, mozzarella di bufala e rucola",
            // "type_id" => 12,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 40,
            "name" => "Focaccia Ortolana",
            "price" => "7.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Verdure grigliate",
            // "type_id" => 12,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 41,
            "name" => "Focaccia Primavera",
            "price" => "8.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Pomodoro fresco, tonno, rucola e mais",
            // "type_id" => 12,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine focacce
        [
            "id" => 42,
            "name" => "Panino Sombrero",
            "price" => "9.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Prosciutto crudo di Parma 18 mesi, pane con farina 00 lievitato 24h, brie del lodigiano Dop, rucola, pomodoro, crema di tartufo e granella di noci",
            // "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 43,
            "name" => "Panino Animalier",
            "price" => "10.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Capocollo al malvasia, pane integrale ai farri antichi, zucchine grigliate, bombetta calabra, crema di parmigiano reggiano dop, granella di mandorle e basilico",
            // "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 44,
            "name" => "Panino Smoking",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Pulled pork, focaccia all’alga spirulina, cavolo cappuccio viola, stracchino, marmellata di peperoni, maionese della casa e granella di pistacchio",
            // "type_id" => 14,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine panini
        [
            "id" => 45,
            "name" => "Macedonia",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Mela , pera , banana, fragole, sciroppo di arancia, sciroppo di limone, zucchero",
            // "type_id" => 15,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine frutta
        [
            "id" => 46,
            "name" => "Piatto Kebab",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Kebab di pollo 100% italiano, pomodori, cipolla, lattuga, salsa yogurt, salsa piccante.",
            // "type_id" => 16,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 47,
            "name" => "Panino Kebab",
            "price" => "5.0",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Kebab di pollo 100% italiano, pomodori, cipolla, lattuga, salsa yogurt, salsa piccante.",
            // "type_id" => 16,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 48,
            "name" => "Piadina Kebab",
            "price" => "5.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Kebab di pollo 100% italiano, cipolla caramellata, lattuga, maionese limone e pepe nero by Heinz.",
            // "type_id" => 16,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine kebab
        [
            "id" => 49,
            "name" => "Nigiri Salmone",
            "price" => "5.90",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "3 pezzi - riso e salmone",
            // "type_id" => 18,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 50,
            "name" => "California Roll",
            "price" => "8.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "9 pezzi - roll di surimi, avocado, cetriolo e sesamo",
            // "type_id" => 18,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 51,
            "name" => "Futomaki Salmone Affumicato",
            "price" => "5.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "5 pezzi - riso, alga, mix di salmone e formaggio spalmabile, avocado, cetriolo e carota",
            // "type_id" => 18,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 52,
            "name" => "Gunkan Spicy Ebi e Avocado",
            "price" => "6.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "3 pezzi - riso, tartare di mazzancolla tropicale, avocado, spicy mayo e zucchina",
            // "type_id" => 18,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 53,
            "name" => "Ebi in Tempura Crunch Roll",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "9 pezzi - roll di gamberi in tempura con avocado, cetriolo, ricoperto con mayo piccante, salsa unagi e cipolla fritta croccante",
            // "type_id" => 18,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine sushi
        [
            "id" => 54,
            "name" => "Panino ca Mieusa",
            "price" => "4.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Milza, limone, grana",
            // "type_id" => 20,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 55,
            "name" => "Hamburger Top",
            "price" => "5.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Hamburger, formaggio, pomodoro e insalata",
            // "type_id" => 20,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 56,
            "name" => "Toast Americano",
            "price" => "4.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "maxi toast con prosciutto cotto e fontina",
            // "type_id" => 20,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine street food
        [
            "id" => 57,
            "name" => "Koshari Grande",
            "price" => "10.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Cipolle croccanti, ceci, salsa al pomodoro, pasta filini lenticchie, ditaloni rigati e riso bianco",
            // "type_id" => 21,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 58,
            "name" => "Koshari 101",
            "price" => "11.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "cipolle croccanti, ceci, salsa al pomodoro, pasta filini lenticchie, ditaloni rigati e riso bianco",
            // "type_id" => 21,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine koshari per ristorante egiziano
        [
            "id" => 59,
            "name" => "El Dorado",
            "price" => "12.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Tinga di pollo, crema di fagioli, cavolo rosso alla Britos, pico de gallo e salsa a scelta",
            // "type_id" => 22,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 60,
            "name" => "Reynosa",
            "price" => "12.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Tinga di pollo vegano, peperoncino jalapeÃ±o, cavolo rosso alla Britos, cipolle grigliate, pico de gallo e salsa a scelta",
            // "type_id" => 22,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine tacos per messicano
        [
            "id" => 61,
            "name" => "Houston",
            "price" => "14.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Pulled pork, riso alla messicana, fagioli neri alla messicana, pico de frutta, formaggio ranchero, peperoncino jalapenoe salsa piccante",
            // "type_id" => 23,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 62,
            "name" => "La Cruz",
            "price" => "14.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Tinga di pollo vegano, riso alla messicana, crema di fagioli, pico de gallo, cipolle grigliate, insalata iceberg e salsa piccante",
            // "type_id" => 23,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine burritos per messicano
        [
            "id" => 63,
            "name" => "Cornetto Ischitano Vuoto",
            "price" => "2.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 0,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 64,
            "name" => "Pasticciotto alla Crema e Amarena",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 0,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 65,
            "name" => "Fagottino alla Marmellata",
            "price" => "1.80",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 0,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine colazione
        [
            "id" => 66,
            "name" => "Acqua Naturale",
            "price" => "1.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "50 cl",
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 67,
            "name" => "Acqua Frizzante",
            "price" => "1.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "50 cl",
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 68,
            "name" => "Coca Cola",
            "price" => "1.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "33 cl",
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 69,
            "name" => "Coca Cola Zero",
            "price" => "1.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "33 cl",
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 70,
            "name" => "Crodino",
            "price" => "3.00",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => null,
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        [
            "id" => 71,
            "name" => "Birra",
            "price" => "2.50",
            "available" => '1',
            "discount" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "66 cl",
            // "type_id" => 7,
            // "menu_id" => null,
            "restaurant_id" => null,
        ],
        // fine bevande




    ],
    'users' => [
        [
            'name' => 'Pippo',
            'lastname' => 'Mustica',
            'password' => 'deliveboo',
            'email' => 'pippo.mustica@gmail.com'
        ],
        [
            'name' => 'Herbert',
            'lastname' => 'Fonzarelli',
            'password' => 'deliveboo',
            'email' => 'herbert.fonzarelli@gmail.com'
        ],
        [
            'name' => 'Melo',
            'lastname' => 'Fonte',
            'password' => 'deliveboo',
            'email' => 'melo.fonte@gmail.com'
        ],
        [
            'name' => 'Gino',
            'lastname' => 'Fantozzi',
            'password' => 'deliveboo',
            'email' => 'gino.fantozzi@gmail.com'
        ],
        [
            'name' => 'Simone',
            'lastname' => 'Gallo',
            'password' => 'deliveboo',
            'email' => 'simone.gallo@gmail.com'
        ],
        [
            'name' => 'Giuseppe',
            'lastname' => 'Ferro',
            'password' => 'deliveboo',
            'email' => 'giuseppe.ferro@gmail.com'
        ],
        [
            'name' => 'Ricco',
            'lastname' => 'Galluzzo',
            'password' => 'deliveboo',
            'email' => 'ricco.galluzzo@gmail.com'
        ],
        [
            'name' => 'Riccardo',
            'lastname' => 'Palazzi',
            'password' => 'deliveboo',
            'email' => 'riccardo.palazzi@gmail.com'
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Marino',
            'password' => 'deliveboo',
            'email' => 'michele.marino@gmail.com'
        ],
        [
            'name' => 'Basilio',
            'lastname' => 'Matassa',
            'password' => 'deliveboo',
            'email' => 'basilio.matassa@gmail.com'
        ]
    ],



    'restaurants' => [

        [
            "id" => 1,
            "user_id" => 1,
            "restaurant_name" => "Pizzeria L'Angolo", // pizza italiano
            "address" => "Via Emilia Ponente 120, Bologna, 40133",
            "p_iva" => "92255625968",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Pizza·Italiano·Sandwich",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:45",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 2,
            "restaurant_name" => "Kingu Sushi", // sushi 
            "address" => "Via Cosenz, 60, 98076 Sant'Agata di Militello ME",
            "p_iva" => "36749577791",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Ristorante di sushi",
            "delivery_price" => null,
            "opening_time" => "10:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 3,
            "restaurant_name" => "Berbere' Pizzeria", // pizza fritti
            "address" => "6a Piazza di Porta Saragozza, Bologna, 40123",
            "p_iva" => "79554564471",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Italiano·Pizza",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "24:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 4,
            "restaurant_name" => "Koshari", // hamburger egiziano
            "address" => "Via Panfilo Castaldi 23, Milano, 20124",
            "p_iva" => "32661682277",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Hamburger, Egiziano",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 5,
            "restaurant_name" => "Vima's Food", // africano, fa insalate e piadine
            "address" => "Via Paolo Giovio, 1, Milano, 20144",
            "p_iva" => "37221289354",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Africano·Insalate·Piadina",
            "delivery_price" => null,
            "opening_time" => "10:00",
            "closing_time" => "22:15",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 6,
            "restaurant_name" => "Bomaki - Garibaldi",  // Giapponese
            "address" => "Corso Garibaldi 79, Milano, 20121",
            "p_iva" => "33724782362",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Stai cercando Uramaki, burritos e sushi nippo-brasiliano a domicilio? Con Bomaki - Garibaldi di Milano non hai più bisogno di cercare.",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "24:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 7,
            "restaurant_name" => "Sweetburger", // americano hamburger
            "address" => "Piazza Ventiquattro Maggio 1/8, Milano, 20122",
            "p_iva" => "74841879582",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Stai cercando Hamburger e Dolci a domicilio? Con Sweetburger di Milano non hai più bisogno di cercare. Vai al suo menù su Just Eat e fai il tuo ordine ora.",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 8,
            "restaurant_name" => "My Heart Burger Normale e Senza Glutine", // hamburger ma senza glutine!!!!!!!!!!!!!
            "address" => "Via di Porta Pinciana, 14",
            "p_iva" => "46644626375",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Voglia di Hamburger ma quella di cucinare è scappata di casa? Non temere!",
            "delivery_price" => null,
            "opening_time" => "10:00",
            "closing_time" => "23:59",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 9,
            "restaurant_name" => "Istanbul Kebab",  // pizza kebab
            "address" => "Via Piero della Francesca, 23, Milano, 20154",
            "p_iva" => "83853142392",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Voglia di Pizza e Kebab a domicilio a Milano? Scopri il menu di Istanbul Kebab e ordina comodamente online. Puoi pagare anche con carta di credito!",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:15",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ],
        [
            "id" => 1,
            "user_id" => 10,
            "restaurant_name" => "Mergellina Bakery", // dolci bakery
            "address" => "Viale Bligny 13, Milano, 20136",
            "p_iva" => "44378213487",
            "contact_phone" => null,
            "image" => "https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769",
            "description" => "Stai cercando Dolci e Rosticceria a domicilio? Con Mergellina Bakery® di Milano non hai più bisogno di cercare.",
            "delivery_price" => null,
            "opening_time" => "12:00",
            "closing_time" => "22:00",
            "min_price_order" => null,
            // "product_id" => null,
            // "category_id" => null,
            // "customer_order_id" => null,
            "rating" => null,
        ]

    ]
];
